packages:
  - '.'

allowBuilds:
  '@parcel/watcher': false
  canvas: false
  core-js: false
  es5-ext: false
  esbuild: false
  less: false
  puppeteer: true
  v-code-diff: false
  vue-demi: false
  x-data-spreadsheet: false
